services:
  app:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - 3001:3000
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - auth-network

  database:
    image: mysql:5.7.32
    container_name: database
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge